# Change these first
owner: fullmoondev # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://www.fullmoon.dev/
  - name: Accounts
    url: https://www.fullmoon.dev/accounts/
  - name: Help Desk
    url: https://www.fullmoon.dev/help/
  - name: Protected
    url: https://protected.fullmoon.dev/
    expectedStatusCodes:
      - 200
      - 401
  - name: Profile API
    url: https://profile.live.net.co/info
  - name: Online Live Service API
    url: https://ols.live.net.co/info
  - name: Live Store Assets
    url: https://apollo.fullmoon.dev/
  - name: Live Store API
    url: https://store-api.live.net.co/info
  - name: Live Store Ruby CDN
    url: https://ruby.cdn.apollo.fullmoon.dev/
    expectedStatusCodes:
      - 200
      - 403
      - 401
  - name: Global Assets
    url: https://assets.fullmoon.dev/
  - name: Global CDN
    url: https://c.live.net.co/
  - name: Waddle Penguins Island - Website
    url: https://waddlepenguins.me/
  - name: Waddle Penguins Island - API
    url: https://api.waddlepenguins.me/
  - name: Waddle Penguins Island - Game Server
    url: $GAMESERVER_URL
  - name: Waddle Penguins Island - Content
    url: https://cdn.waddlepenguins.me/
    expectedStatusCodes:
      - 200
      - 403
      - 404
  - name: Waddle Penguins Island - Content CDN
    url: https://wpi2.cdn.dink.cf/
    expectedStatusCodes:
      - 200
      - 403
      - 404
  - name: Club Penguin Atake - Website
    url: https://cpatake.boo/
  - name: Club Penguin Atake - AS1
    url: https://as1.cpatake.boo/
  - name: Club Penguin Atake - AS2
    url: https://as2.cpatake.boo/
  - name: Club Penguin Atake - AS3
    url: https://as3.cpatake.boo/
  - name: Club Penguin Atake - App
    url: https://app.cpatake.boo/
  - name: Club Penguin Atake TV
    url: https://tv.cpatake.boo/
  - name: Club Penguin Atake Web Services
    url: https://webservice.cpatake.boo/
  - name: Club Penguin Atake TV - Video CDN
    url: https://cdn.tv.cpatake.boo/
    expectedStatusCodes:
      - 200
      - 403
  - name: Club Penguin Atake - Legacy CDN
    url: https://legacy.cdn.cpatake.tk/
    expectedStatusCodes:
      - 200
      - 403
  - name: Club Penguin Atake - Vanilla CDN
    url: https://vanilla.cdn.cpatake.tk/
    expectedStatusCodes:
      - 200
      - 403
  - name: Club Penguin Atake - Antique CDN
    url: https://antique.cdn.cpatake.tk/
    expectedStatusCodes:
      - 200
      - 403
  - name: Club Penguin Atake - Experimental Penguins
    url: https://ep.cpatake.boo/
  - name: Club Penguin Atake - Penguin Chat
    url: https://pc.cpatake.boo/
  - name: Club Penguin Atake - Penguin Chat 3
    url: https://pc3.cpatake.boo/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fullmoon.dev
  # baseUrl: /your-repo-name
  favicon: https://cdn.fullmoon.dev/images/moonlight/social-alt.jpg
  logoUrl: https://cdn.fullmoon.dev/images/moonlight/social-alt.jpg
  name: Fullmoon Status
  introTitle: "You and your world. Always together."
  introMessage: Check the status of our services here.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://www.fullmoon.dev/?ref=status
    - title: Help
      href: https://www.fullmoon.dev/help/?ref=status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
